[phases.setup]
  nixPkgs = ["nodejs_20", "yarn"]

  [phases.build]
  cmds = [
      "cd frontend && yarn install --frozen-lockfile",
      "cd frontend && yarn build"
  ]

  [start]
  cmd = "nginx -g 'daemon off;'"

  [build.env]
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"
  INLINE_RUNTIME_CHUNK = "false"

  [[build.env]]
  name = "REACT_APP_API_URL"
  value = "http://ksg884s4g0ggs8k8o8wgo4s8.109.123.245.9.sslip.io/api"
