  [phases.setup]
  nixPkgs = ["nodejs_20", "yarn"]

  [phases.build]
  cmds = ["cd frontend && yarn install --frozen-lockfile && yarn build"]

  [start]
  cmd = "cd frontend && npx serve -s build -l 3000"
